<a href="https://colab.research.google.com/github/majorquev/DBDC_202504_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/Clase2/Clase_2_01_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales <br>
**E-mail ayudante:** rumorale1@gmail.com



### 3.2 Matrices

En R, así como en otros lenguajes de programación, una matriz es básicamente un arreglo bi-dimensional, donde las entradas horizontales se entienden como filas y las verticales como columnas. Es posible imaginar una matriz como un arreglo de vectores como columnas (o filas) del mismo largo.

 * ¿Qué se guarda en una matriz?<br>
    Sólo datos de un mismo tipo.
     
 * ¿Cómo se declara una matriz?<br>
    Se puede definir de varias maneras, indicando los elementos que la componen, o combinando vectores como filas o columnas.

 * ¿Cómo se accede a sus elementos?<br>
    Indicando la posición del vector fila, seguido de la posición del vector columna (como es usual).

In [1]:
# 3.2 Matrices ------------
#?matrix de dos filas y 3 columnas, parametros ncol, nrow y byrow
# recibe un vector de elementos
A <- matrix(c(1,1,2,3,5,8), ncol = 3, nrow = 2)
A



[,1] [,2] [,3]
[1,] 1    2    5   
[2,] 1    3    8

In [3]:
B <- matrix(c(1,1,2,3,5,8), ncol = 3, nrow = 2, byrow = T)
B

[,1] [,2] [,3]
[1,] 1    1    2   
[2,] 3    5    8

In [4]:
# clase y atributo dim
class(A)

[1] "matrix" "array"

In [5]:
dim(A)

[1] 2 3

In [6]:
# Genere dos vectores del mismo largo y forme una matriz.

c1 <- c(1,2,3)
c2 <- c(5,10,15)
c3 <- c(7,8,9)



In [8]:
# funciones cbind() [une vectores como columnas]
# y rbind() [une vectores como filas] (pensadas para matrices)
#?cbind

M <- cbind(c1,c2,c3)
M

c1 c2 c3
[1,] 1   5 7 
[2,] 2  10 8 
[3,] 3  15 9

In [9]:
f1 <- c(1,2,3)
f2 <- c(4,1,3)

In [11]:
MR <- rbind(f1,f2)
MR

[,1] [,2] [,3]
f1 1    2    3   
f2 4    1    3

In [12]:
# NOTA: Podemos añadir una fila/columna a una matriz existente
f3 <- c(0,1,0)
rbind(MR,f3)

[,1] [,2] [,3]
f1 1    2    3   
f2 4    1    3   
f3 0    1    0

In [14]:
MR <- rbind(MR,f3)
MR

[,1] [,2] [,3]
f1 1    2    3   
f2 4    1    3   
f3 0    1    0

In [15]:
# si combinamos vectores de distinto largo?
# R recicla valores (recordar explicación)

c22 <- c(100,200)
c22
c1




[1] 100 200

[1] 1 2 3

In [16]:
cbind(c1,c22)

Warning message in cbind(c1, c22):
“number of rows of result is not a multiple of vector length (arg 2)”


c1 c22
[1,] 1  100
[2,] 2  200
[3,] 3  100

In [17]:
# función diag para la definición de matrices diagonales
#?diag

diag(c(1,1,2,3,5,8))



[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    0    0    0    0    0   
[2,] 0    1    0    0    0    0   
[3,] 0    0    2    0    0    0   
[4,] 0    0    0    3    0    0   
[5,] 0    0    0    0    5    0   
[6,] 0    0    0    0    0    8

In [21]:
# Podemos acceder a los elementos de una matriz
# indicando la posición de la fila y la columna de la casilla correspondiente.
# Ejemplo: # quiero rescatar el elemento "(2,1)"
M
M[2,1]


c1 c2 c3
[1,] 1   5 7 
[2,] 2  10 8 
[3,] 3  15 9

c1 
 2

In [22]:
# CUIDADO:No es lo mismo que
M[c(2,1)] # NO LO HAGAN

[1] 2 1

In [24]:
# Para acceder a una fila completa. Ej: Extraer la tercera fila
M[3,]

# Para acceder a una columna completa. Ej: Extraer la 2da columna
M[,2]


c1 c2 c3 
 3 15  9

[1]  5 10 15

In [26]:
#Recordemos que podemos actualizar elementos de un vector como:

# quiero cambiar el 15 por un -99 (el 15 de la pos 3,2)
M[3,2] <- -99


In [27]:
M

c1 c2  c3
[1,] 1    5 7 
[2,] 2   10 8 
[3,] 3  -99 9

In [32]:
# Acceso mediante nombres
colnames(M)
rownames(M)

[1] "c1" "c2" "c3"

NULL

In [33]:
# Podemos asignar un vector de nombres en rownames
rownames(M) <- c("f1","f2","f3")

In [34]:
M

c1 c2  c3
f1 1    5 7 
f2 2   10 8 
f3 3  -99 9

In [36]:
# Acceso mediante nomnbres
# Elemento de la fila "f2" y columna "c3"

M["f2","c3"]


[1] 8

ERROR: Error in M["c3", "f2"]: subscript out of bounds


In [41]:
# Acceso mediante "indicatrices" lógicas
#Quiero obtener los elementos (3,2) y (2,3) de M
# 1: Crear una matriz de 3x3 con TRUE en dichas posiciones y FALSE en las restantes.
M
dim(M)

c1 c2  c3
f1 1    5 7 
f2 2   10 8 
f3 3  -99 9

[1] 3 3

In [ ]:
mat_ind <- matrix(c(F,F,F,F,F,T,F,T,F), ncol = 3, nrow = 3)
mat_ind

In [43]:
# Otra alternativa, sería crear vector para luego disponerlos como filas/columnas con rbind/cbind

t1 <- c(F,F,F)
t2 <- c(F,F,T)
t3 <- c(F,T,F)

mat_ind2 <- rbind(t1,t2,t3)
mat_ind2


[,1]  [,2]  [,3] 
t1 FALSE FALSE FALSE
t2 FALSE FALSE  TRUE
t3 FALSE  TRUE FALSE

In [40]:
M[mat_ind]

[1] -99   8

In [48]:
M

c1 c2  c3
f1 1    5 7 
f2 2   10 8 
f3 3  -99 9

In [46]:
# Ubicar los elemtnos menores a 3
M < 3

c1    c2    c3   
f1  TRUE FALSE FALSE
f2  TRUE FALSE FALSE
f3 FALSE  TRUE FALSE

In [47]:
# podemos entonces extraer los elmentos que cumplen la condición  (ser menor que 3)
M[M < 3]

[1]   1   2 -99

**Álgebra de matrices**

Las operaciones suma (resta) y ponderación por escalar se llevan cabo mediante los mismos operadores utilizados para valores numéricos y vectores (+,-,*, /). Para multiplicar matrices en cambio, se utiliza el operador %*%, mientras que para invertirlas se utiliza la función solve(), t() para transponer y det() para el cálculo del determinante en el caso de matrices cuadradas.

In [ ]:
# transponer una matriz


In [ ]:
# 3.2 Álgbra de matrices  ------------
# Ejemplo simple de álgebra de matrices



In [50]:
# Multiplicación de matrices
M ; MR # multiplicación componente a componente


c1 c2  c3
f1 1    5 7 
f2 2   10 8 
f3 3  -99 9

[,1] [,2] [,3]
f1 1    2    3   
f2 4    1    3   
f3 0    1    0

In [52]:
M + MR
M - MR
M * MR
M / MR

c1 c2  c3
f1 2    7 10
f2 6   11 11
f3 3  -98  9

c1 c2   c3
f1  0    3 4 
f2 -2    9 5 
f3  3 -100 9

c1 c2  c3
f1 1   10 21
f2 8   10 24
f3 0  -99  0

c1  c2    c3      
f1 1.0   2.5 2.333333
f2 0.5  10.0 2.666667
f3 Inf -99.0      Inf

In [ ]:
# podemos calcular determinantes
# ?det



In [ ]:
# Podemos invertir matrices
# ?solve
