<a href="https://colab.research.google.com/github/majorquev/DBDC_202504_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/Clase2/Clase_2_02_listas_y_dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales <br>
**E-mail ayudante:** rumorale1@gmail.com


## 5. Listas y Dataframes

### 5.1 Listas

Hasta aquí contamos con dos tipos de objetos para almacenar datos; vectores y matrices. Sin embargo, en ambos casos se tiene la limitante de que no es posible combinar distintos tipos de datos en diferentes entradas. Un objeto que permite una mayor flexibilidad son las listas. En R, una lista es básicamente un arreglo unidimensional, donde en cada entrada es posible almacenar distintos **objetos** (los cuales a su vez pueden almacenar distintos tipos de datos (u otros objetos).
En resumen,

   * ¿Qué son?<br>
    Arreglos unidimensionales que guardan distintos tipos de datos u objetos.<br>

   * ¿Cómo se declaran?<br>
    Se pueden declarar mediante el comando list() o combinando listas existentes. <br>
    
   * ¿Cómo se accede a sus elementos?<br>
    Usando [ ] (retorna lista), o bien usando [ [ ] ] (retorna el objeto).
    En cada caso se puede indicar la posición o nombre del objeto que se quiere rescatar.<br>
    Otra manera es mediante el símbolo $ seguido del nombre del objeto.



In [1]:
# 5. Listas y dataframes ------------
# 5.1 Listas  ------------
# Cómo declarar una lista (comando list() )
#num,letra, pl, mat, lista
# Podemos guardar los objetos en slots con nombres (recomendado)
l1 <- list(num = 5,
           letra = c("A","B"),
           pl = "hola",
           mat = diag(1:5),
           lista = list(x = -1:3, fecha = as.Date("2025-05-29")) )

In [2]:

l1

$num
[1] 5

$letra
[1] "A" "B"

$pl
[1] "hola"

$mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    2    0    0    0
[3,]    0    0    3    0    0
[4,]    0    0    0    4    0
[5,]    0    0    0    0    5

$lista
$lista$x
[1] -1  0  1  2  3

$lista$fecha
[1] "2025-05-29"

In [3]:
# estructura
str(l1)

List of 5
 $ num  : num 5
 $ letra: chr [1:2] "A" "B"
 $ pl   : chr "hola"
 $ mat  : int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ lista:List of 2
  ..$ x    : int [1:5] -1 0 1 2 3
  ..$ fecha: Date[1:1], format: "2025-05-29"


In [5]:
LETTERS # Es un vector pre-definido con el alfabeto ne mayúsculas
letters # Es un vector pre-definido con el alfabeto ne minúsculas

[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

In [6]:
# Podemos definir listas sin nombres en las entradas
l2 <- list(-5:0, LETTERS)


In [7]:
str(l2)

List of 2
 $ : int [1:6] -5 -4 -3 -2 -1 0
 $ : chr [1:26] "A" "B" "C" "D" ...


In [8]:
l2

[[1]]
[1] -5 -4 -3 -2 -1  0

[[2]]
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [10]:
# Podemos rescatar los nombres
names(l1)
names(l2)

[1] "num"   "letra" "pl"    "mat"   "lista"

NULL

In [11]:
# podemos rescatar los largos
length(l1)
length(l2)

[1] 5

[1] 2

In [13]:
# Podemos combinar (unir) listas
c(l1 , l2)

$num
[1] 5

$letra
[1] "A" "B"

$pl
[1] "hola"

$mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    2    0    0    0
[3,]    0    0    3    0    0
[4,]    0    0    0    4    0
[5,]    0    0    0    0    5

$lista
$lista$x
[1] -1  0  1  2  3

$lista$fecha
[1] "2025-05-29"


[[6]]
[1] -5 -4 -3 -2 -1  0

[[7]]
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [14]:
# como el largo de l2 es 2 [ lenght(l2)]
names(l2) <- c("c6","c7")

In [15]:
# Podemos crear una lista l3, con las dos anteriores unidas.
l3 <- c(l1,l2)

In [16]:
str(l3)

List of 7
 $ num  : num 5
 $ letra: chr [1:2] "A" "B"
 $ pl   : chr "hola"
 $ mat  : int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ lista:List of 2
  ..$ x    : int [1:5] -1 0 1 2 3
  ..$ fecha: Date[1:1], format: "2025-05-29"
 $ c6   : int [1:6] -5 -4 -3 -2 -1 0
 $ c7   : chr [1:26] "A" "B" "C" "D" ...


In [20]:
# Acceso mediante posición
# Nos gustaría rescatar el elemtno de posición 4
l3[4]
class(l3[4])

$mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    2    0    0    0
[3,]    0    0    3    0    0
[4,]    0    0    0    4    0
[5,]    0    0    0    0    5

[1] "list"

In [22]:
l3[c(1,3,5)]

$num
[1] 5

$pl
[1] "hola"

$lista
$lista$x
[1] -1  0  1  2  3

$lista$fecha
[1] "2025-05-29"

In [27]:
# NOTA lista[.] retorna un lista con un elemento,
# lista[[.]] retorna el elmento de la lista lista[.]
l3[4]# Una lista con una matriz (lista de largo 1)


$mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    2    0    0    0
[3,]    0    0    3    0    0
[4,]    0    0    0    4    0
[5,]    0    0    0    0    5

In [28]:

l3[[4]] # la matriz que está dentro de la lista l3[4]


[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    0    0    0   
[2,] 0    2    0    0    0   
[3,] 0    0    3    0    0   
[4,] 0    0    0    4    0   
[5,] 0    0    0    0    5

In [25]:
l3[[4]] + 1

[,1] [,2] [,3] [,4] [,5]
[1,] 2    1    1    1    1   
[2,] 1    3    1    1    1   
[3,] 1    1    4    1    1   
[4,] 1    1    1    5    1   
[5,] 1    1    1    1    6

In [26]:
l3

$num
[1] 5

$letra
[1] "A" "B"

$pl
[1] "hola"

$mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    2    0    0    0
[3,]    0    0    3    0    0
[4,]    0    0    0    4    0
[5,]    0    0    0    0    5

$lista
$lista$x
[1] -1  0  1  2  3

$lista$fecha
[1] "2025-05-29"


$c6
[1] -5 -4 -3 -2 -1  0

$c7
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [ ]:
# de la lista l3[[5]], quieo el vector que está en el slot llamado "x" (primer elemento)
l3[5] #es una lista con el objeto (otra lista)


In [29]:
l3[[5]] # El objeto que está en el slot 5 (es una lista)

$x
[1] -1  0  1  2  3

$fecha
[1] "2025-05-29"

In [30]:
l3[[5]][1] # lista con el objeto de dicha posición (un vector)



$x
[1] -1  0  1  2  3

In [31]:
l3[[5]][[1]] # El objeto buscado


[1] -1  0  1  2  3

In [32]:
# Como lo anterior es un vector. Si queremos el elemtno de posición  4
l3[[5]][[1]][4]

[1] 2

In [33]:
# Acceso mediante nombre
# Replicamos los casos anteriores
# Matriz
names(l3)


[1] "num"   "letra" "pl"    "mat"   "lista" "c6"    "c7"

In [34]:
l3["mat"] # Retorna una lista con la matriz

$mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    2    0    0    0
[3,]    0    0    3    0    0
[4,]    0    0    0    4    0
[5,]    0    0    0    0    5

In [35]:
l3[["mat"]]# Retorna la matriz

[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    0    0    0   
[2,] 0    2    0    0    0   
[3,] 0    0    3    0    0   
[4,] 0    0    0    4    0   
[5,] 0    0    0    0    5

In [36]:
# Rescatando "x" de la sublista "lista"
str(l3)

List of 7
 $ num  : num 5
 $ letra: chr [1:2] "A" "B"
 $ pl   : chr "hola"
 $ mat  : int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ lista:List of 2
  ..$ x    : int [1:5] -1 0 1 2 3
  ..$ fecha: Date[1:1], format: "2025-05-29"
 $ c6   : int [1:6] -5 -4 -3 -2 -1 0
 $ c7   : chr [1:26] "A" "B" "C" "D" ...


In [37]:
l3[["lista"]][["x"]]

[1] -1  0  1  2  3

In [39]:
# acceso vía "$"
l3$mat # Retorna directamente el objeto que está en la casilla de la lista.
# Es equivalente a
l3[["mat"]]
l3[[4]]




[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    0    0    0   
[2,] 0    2    0    0    0   
[3,] 0    0    3    0    0   
[4,] 0    0    0    4    0   
[5,] 0    0    0    0    5

[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    0    0    0   
[2,] 0    2    0    0    0   
[3,] 0    0    3    0    0   
[4,] 0    0    0    4    0   
[5,] 0    0    0    0    5

[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    0    0    0   
[2,] 0    2    0    0    0   
[3,] 0    0    3    0    0   
[4,] 0    0    0    4    0   
[5,] 0    0    0    0    5

In [40]:
str(l3)

List of 7
 $ num  : num 5
 $ letra: chr [1:2] "A" "B"
 $ pl   : chr "hola"
 $ mat  : int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ lista:List of 2
  ..$ x    : int [1:5] -1 0 1 2 3
  ..$ fecha: Date[1:1], format: "2025-05-29"
 $ c6   : int [1:6] -5 -4 -3 -2 -1 0
 $ c7   : chr [1:26] "A" "B" "C" "D" ...


In [43]:
# nuestro ejemplo del "x"
l3$lista$x
#Es equivalente a
l3[["lista"]][["x"]]
l3[[5]][[1]]

[1] -1  0  1  2  3

[1] -1  0  1  2  3

[1] -1  0  1  2  3

In [45]:
# para saber el largo de la lista/vector
length(l3)
# Para obtener los nombres de la lista
names(l3)
# si quisiéramos renombrar los slots:


[1] 7

[1] "num"   "letra" "pl"    "mat"   "lista" "c6"    "c7"

In [48]:
# Cambiar el nombre de la entrada llamada "lista", por "sub_l"
names(l3)[5] <- "sub_l"


In [49]:
str(l3)

List of 7
 $ num  : num 5
 $ letra: chr [1:2] "A" "B"
 $ pl   : chr "hola"
 $ mat  : int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ sub_l:List of 2
  ..$ x    : int [1:5] -1 0 1 2 3
  ..$ fecha: Date[1:1], format: "2025-05-29"
 $ c6   : int [1:6] -5 -4 -3 -2 -1 0
 $ c7   : chr [1:26] "A" "B" "C" "D" ...


In [56]:
# Cambiemos el nombre de "x" de la lista sub_l, por "x_2"

names(l3[["sub_l"]])[1] <- "x_2"
#Equivalentemente #     names(l3$sub_l)[1] <- "x_2"

In [57]:
str(l3)

List of 7
 $ num  : num 5
 $ letra: chr [1:2] "A" "B"
 $ pl   : chr "hola"
 $ mat  : int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ sub_l:List of 2
  ..$ x_3  : int [1:5] -1 0 1 2 3
  ..$ fecha: Date[1:1], format: "2025-05-29"
 $ c6   : int [1:6] -5 -4 -3 -2 -1 0
 $ c7   : chr [1:26] "A" "B" "C" "D" ...


In [ ]:
# También podemos crear nuevos "slots"
# (work around) Una alternativa es creando una nueva lista y luego unirla a la existente


#      l4 <- list(nuevo = "otro valor")
#
#      l3_ <- c(l3,l4)



In [64]:
str(l3)

List of 7
 $ num  : num 5
 $ letra: chr [1:2] "A" "B"
 $ pl   : chr "hola"
 $ mat  : int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ sub_l:List of 2
  ..$ x_3  : int [1:5] -1 0 1 2 3
  ..$ fecha: Date[1:1], format: "2025-05-29"
 $ c6   : int [1:6] -5 -4 -3 -2 -1 0
 $ c7   : chr [1:26] "A" "B" "C" "D" ...


In [66]:
## Indicando nombre en [[]] o con "$" y luego asignando
l3[["nueva"]] <- "otro valor"

In [67]:
str(l3)

List of 8
 $ num  : num 5
 $ letra: chr [1:2] "A" "B"
 $ pl   : chr "hola"
 $ mat  : int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ sub_l:List of 2
  ..$ x_3  : int [1:5] -1 0 1 2 3
  ..$ fecha: Date[1:1], format: "2025-05-29"
 $ c6   : int [1:6] -5 -4 -3 -2 -1 0
 $ c7   : chr [1:26] "A" "B" "C" "D" ...
 $ nueva: chr "otro valor"


In [69]:
l3$nueva_2 <- 2025

In [70]:
str(l3)

List of 9
 $ num    : num 5
 $ letra  : chr [1:2] "A" "B"
 $ pl     : chr "hola"
 $ mat    : int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ sub_l  :List of 2
  ..$ x_3  : int [1:5] -1 0 1 2 3
  ..$ fecha: Date[1:1], format: "2025-05-29"
 $ c6     : int [1:6] -5 -4 -3 -2 -1 0
 $ c7     : chr [1:26] "A" "B" "C" "D" ...
 $ nueva  : chr "otro valor"
 $ nueva_2: num 2025


In [74]:
# podemos borrar un slot
l3$nueva_2 <- NULL
l3[["nueva"]] <- NULL

In [75]:
l3

$num
[1] 5

$letra
[1] "A" "B"

$pl
[1] "hola"

$mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    2    0    0    0
[3,]    0    0    3    0    0
[4,]    0    0    0    4    0
[5,]    0    0    0    0    5

$sub_l
$sub_l$x_3
[1] -1  0  1  2  3

$sub_l$fecha
[1] "2025-05-29"


$c6
[1] -5 -4 -3 -2 -1  0

$c7
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

### 5.2 Dataframes

Un dataframe es un caso particular de una lista, donde los objetos de cada entrada corresponden a vectores de datos del mismo largo. E este caso cada vector corresponde a una columna del data.frame, mientras que la cantidad de filas corresponde al largo común de los vectores de cada entrada. El objeto resultante es una *tabla*, de ahora en adelante *data.frame*, cuyas columnas poseen distintos tipos de datos entre sí.

 * ¿Cómo se declara un dataframe?<br>
     Mediante la función data.frame(), indicando los vectores que conformarán las columnas.

 * ¿Cómo se accede a los datos de un data.frame?<br>
    Al ser una lista, se puede acceder de la misma manera. Sin embargo también es posible acceder del modo en que se accede a los elementos de una matriz.

In [76]:
# 5.2 Dataframes ----------
# Ejemplo sencillo de definición de un data.frame
# recordar que 1:3 es lo mismo que c(1,2,3)
df <- data.frame(
  nombre = c("miguel", "Tito", "Almendra"),
  edad = c(36,30,25),
  rut = c("11-2","10-k","20-1")
)


In [77]:
df

nombre   edad rut 
1 miguel   36   11-2
2 Tito     30   10-k
3 Almendra 25   20-1

In [79]:
dim(df)
nrow(df)
ncol(df)

[1] 3 3

[1] 3

[1] 3

In [81]:
names(df)
colnames(df)

[1] "nombre" "edad"   "rut"

[1] "nombre" "edad"   "rut"

In [82]:
# Acceso a columnas de un data.frame
## Igual que en una lista
# Ej: Acceder a la columna de pos 2 (el slot 2 en las listas), llamada "edad"
df[[2]]
df[["edad"]]
df$edad

#Nos retorna directamente el "objeto" que corresponde al vector de edades (edad)



[1] 36 30 25

[1] 36 30 25

[1] 36 30 25

In [88]:
df[2]
df["edad"]

edad
1 36  
2 30  
3 25

edad
1 36  
2 30  
3 25

In [87]:
##  Ganamos acceso como matriz
# segunda columna
df[,2]
df[,"edad"]

# segunda fila de df
df[2,]
# segunda fila y segunda columna
df[2,2]
df[2,"edad"]


[1] 36 30 25

[1] 36 30 25

nombre edad rut 
2 Tito   30   10-k

[1] 30

[1] 30

In [90]:
#Podemos crear nuevas columnas , del mismmo modo que creamos "slots" en una lista
df$tiene_mascota <- c(F,T,F)

In [91]:
df

nombre   edad rut  tiene_mascota
1 miguel   36   11-2 FALSE        
2 Tito     30   10-k  TRUE        
3 Almendra 25   20-1 FALSE

In [95]:
#Alternativa
df[["comuna_res"]] <- c("Ñuñoa","La Florida", "Vitacura")

In [96]:
df

nombre   edad rut  tiene_mascota comuna_res
1 miguel   36   11-2 FALSE         Ñuñoa     
2 Tito     30   10-k  TRUE         La Florida
3 Almendra 25   20-1 FALSE         Vitacura

In [97]:
str(df)

'data.frame':	3 obs. of  5 variables:
 $ nombre       : chr  "miguel" "Tito" "Almendra"
 $ edad         : num  36 30 25
 $ rut          : chr  "11-2" "10-k" "20-1"
 $ tiene_mascota: logi  FALSE TRUE FALSE
 $ comuna_res   : chr  "Ñuñoa" "La Florida" "Vitacura"


In [100]:
# podemos seleccionar más de una columna a la vez. Ej: seleccionar nombre y edad
df[c(1,2)]# Como si fuesen dos entradas de una lista
df[,c(1,2)]# Como si fuese una matriz
# Referenciando el nombre de las columnas
df[c("nombre","edad")]# Como si fuesen dos entradas de una lista
df[,c("nombre","edad")]# Como si fuese una matriz

nombre   edad
1 miguel   36  
2 Tito     30  
3 Almendra 25

nombre   edad
1 miguel   36  
2 Tito     30  
3 Almendra 25

nombre   edad
1 miguel   36  
2 Tito     30  
3 Almendra 25

nombre   edad
1 miguel   36  
2 Tito     30  
3 Almendra 25

In [101]:
df

nombre   edad rut  tiene_mascota comuna_res
1 miguel   36   11-2 FALSE         Ñuñoa     
2 Tito     30   10-k  TRUE         La Florida
3 Almendra 25   20-1 FALSE         Vitacura

In [102]:
# podemos utilizar la noción de "indicatrices lógicas" para realizar búsquedas por filas sujeto a alguna condición
#ubicar a los registros cuya edad es mayor o igual a 30.

df[df$edad >= 30,]



nombre edad rut  tiene_mascota comuna_res
1 miguel 36   11-2 FALSE         Ñuñoa     
2 Tito   30   10-k  TRUE         La Florida

In [104]:
df[ df[["edad"]] >= 30,]

nombre edad rut  tiene_mascota comuna_res
1 miguel 36   11-2 FALSE         Ñuñoa     
2 Tito   30   10-k  TRUE         La Florida

In [106]:
#ubicar a los registros cuya edad es mayor o igual a 30 y que tenga mascota
df[df$edad >= 30 & df$tiene_mascota == T,]

nombre edad rut  tiene_mascota comuna_res
2 Tito   30   10-k TRUE          La Florida

In [107]:
#ubicar a los registros cuya edad es mayor o igual a 30 y que tenga mascota. mostrando solamente el rut y la comuna
df[df$edad >= 30 & df$tiene_mascota == T, c("rut","comuna_res")]

rut  comuna_res
2 10-k La Florida

In [108]:
df[df$edad >= 30 & df$tiene_mascota == T, c(3,5)]

rut  comuna_res
2 10-k La Florida

In [109]:
# Ubicar los registros cuya comuna de residencia esté entre las opciones : "Ñuñoa" o "La Florida"
df[df$comuna_res %in% c("Ñuñoa", "La Florida"),]

nombre edad rut  tiene_mascota comuna_res
1 miguel 36   11-2 FALSE         Ñuñoa     
2 Tito   30   10-k  TRUE         La Florida

In [ ]:
# df[,grepl("_", names(df))]

In [115]:
#c(1,5,8,3,11,10) %in% c(7,8,0,1)

[1]  TRUE FALSE  TRUE FALSE FALSE FALSE